version: "3.2"
networks:
  fabric_network:
    external:
      name: fabric_network
services:
  kafka1_ordererorg:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: kafka1.ordererorg.com
    image: hyperledger/fabric-kafka:0.4
    ports:
    - target: 9092
      published: 9092
      protocol: tcp
      mode: host
    networks:
      fabric_network:
        aliases:
        - kafka1.ordererorg.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
    - KAFKA_MESSAGE_MAX_BYTES=519045120
    - KAFKA_REPLICA_FETCH_MAX_BYTES=519045120
    - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_MIN_INSYNC_REPLICAS=2
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.ordererorg.com:2181,zookeeper2.ordererorg.com:2181,zookeeper3.ordererorg.com:2181
    - KAFKA_BROKER_ID=1
    volumes:
    - ./data/kafka1.ordererorg.com:/tmp
  kafka2_ordererorg:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: kafka2.ordererorg.com
    image: hyperledger/fabric-kafka:0.4
    ports:
    - target: 9092
      published: 9092
      protocol: tcp
      mode: host
    networks:
      fabric_network:
        aliases:
        - kafka2.ordererorg.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
    - KAFKA_MESSAGE_MAX_BYTES=519045120
    - KAFKA_REPLICA_FETCH_MAX_BYTES=519045120
    - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_MIN_INSYNC_REPLICAS=2
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.ordererorg.com:2181,zookeeper2.ordererorg.com:2181,zookeeper3.ordererorg.com:2181
    - KAFKA_BROKER_ID=2
    volumes:
    - ./data/kafka2.ordererorg.com:/tmp
  kafka3_ordererorg:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: kafka3.ordererorg.com
    image: hyperledger/fabric-kafka:0.4
    ports:
    - target: 9092
      published: 9092
      protocol: tcp
      mode: host
    networks:
      fabric_network:
        aliases:
        - kafka3.ordererorg.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
    - KAFKA_MESSAGE_MAX_BYTES=519045120
    - KAFKA_REPLICA_FETCH_MAX_BYTES=519045120
    - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_MIN_INSYNC_REPLICAS=2
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.ordererorg.com:2181,zookeeper2.ordererorg.com:2181,zookeeper3.ordererorg.com:2181
    - KAFKA_BROKER_ID=3
    volumes:
    - ./data/kafka3.ordererorg.com:/tmp