version: "3.8"
networks:
  fabric_network:
    external:
      name: fabric_network
services:
  orderer1_ordererorg:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: orderer1.ordererorg.com
    image: hyperledger/fabric-orderer:2.1
    ports:
    - target: 7050
      published: 7050
      protocol: tcp
      mode: host
    networks:
      fabric_network:
        aliases:
        - orderer1.ordererorg.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
    - ORDERER_GENERAL_LOGLEVEL=DEBUG
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
    - ORDERER_KAFAK_RETRY_SHORTTOTAL=30s
    - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
    - ./crypto-config/ordererOrganizations/ordererorg.com/orderers/orderer1.ordererorg.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/ordererorg.com/orderers/orderer1.ordererorg.com/tls:/var/hyperledger/orderer/tls
    - ./data/orderer1.ordererorg.com:/var/hyperledger
  orderer2_ordererorg:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: orderer2.ordererorg.com
    image: hyperledger/fabric-orderer:2.1
    ports:
    - target: 7050
      published: 8050
      protocol: tcp
      mode: host
    networks:
      fabric_network:
        aliases:
        - orderer2.ordererorg.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
    - ORDERER_GENERAL_LOGLEVEL=DEBUG
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
    - ORDERER_KAFAK_RETRY_SHORTTOTAL=30s
    - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
    - ./crypto-config/ordererOrganizations/ordererorg.com/orderers/orderer2.ordererorg.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/ordererorg.com/orderers/orderer2.ordererorg.com/tls:/var/hyperledger/orderer/tls
    - ./data/orderer2.ordererorg.com:/var/hyperledger
  orderer3_ordererorg:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: orderer3.ordererorg.com
    image: hyperledger/fabric-orderer:2.1
    ports:
    - target: 7050
      published: 9050
      protocol: tcp
      mode: host
    networks:
      fabric_network:
        aliases:
        - orderer3.ordererorg.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
    - ORDERER_GENERAL_LOGLEVEL=DEBUG
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
    - ORDERER_KAFAK_RETRY_SHORTTOTAL=30s
    - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
    - ./crypto-config/ordererOrganizations/ordererorg.com/orderers/orderer3.ordererorg.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/ordererorg.com/orderers/orderer3.ordererorg.com/tls:/var/hyperledger/orderer/tls
    - ./data/orderer3.ordererorg.com:/var/hyperledger
  