version: "3.2"
networks:
  fabric_network:
    external:
      name: fabric_network
services:
  fabric_restapi:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: api.fabric.com
    image: node:latest
    ports:
    - "8081:8081"
    networks:
      fabric_network:
        aliases:
        - api.fabric.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network
    - PORT=8081
    working_dir: /project/restapi
    command: 
    - /bin/bash
    - -c
    - |
      npm install
      tsc
      node ./dist/app.js
    volumes:
    - .:/project